stages:
  - build
  - package

variables:

  SPRING_BOOT_JAR_PATH: "build/libs/*.jar"

.default-java-job:

  image: gradle:jdk24-alpine

  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - build/

  before_script:
    - chmod +x gradlew

build-jar-job:
  extends: .default-java-job
  stage: build
  script:
    - ./gradlew clean bootJar
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

package-config-server:
  extends: .default-java-job
  stage: package
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t "$CI_REGISTRY_IMAGE/config-server:$CI_COMMIT_SHORT_SHA" --build-arg JAR_FILE="$SPRING_BOOT_JAR_PATH" .
    - docker push "$CI_REGISTRY_IMAGE/config-server:$CI_COMMIT_SHORT_SHA"