name: eureka-cluster

services:
  eureka-1:
    build:
      context: ./
    container_name: eureka-1
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 15s
      retries: 10
    environment:
      - EUREKA_REPLICAS=http://eureka-2:8762/eureka/
      - REPLICA_ID=1
      - PORT=8761
    restart: unless-stopped
    networks:
      - nexus-dev

  eureka-2:
    build:
      context: ./
    container_name: eureka-2
    ports:
      - "8762:8762"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8762/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 15s
      retries: 10
    environment:
      - EUREKA_REPLICAS=http://eureka-1:8761/eureka/
      - REPLICA_ID=2
      - PORT=8762
    restart: unless-stopped
    networks:
      - nexus-dev

networks:
  nexus-dev:
    external: true