server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/, http://localhost:8762/eureka/}