server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  metrics:
    tags:
      application: eureka-${REPLICA_ID:1}

eureka:
  instance:
    hostname: eureka-${REPLICA_ID:1}
    instance-id: eureka-${REPLICA_ID:1}
    appname: eureka
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-2:8762/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 5

logging:
  level:
    root: debug
    web: debug